language: objective-c
git:
  depth: 2
branches:
  only:
    - master
    - dev
script: 
    - xcodebuild -workspace ApiAI.xcworkspace -scheme ApiAITests -sdk iphonesimulator build test
notifications:
    email: false