language: objective-c
bundler_args: --retry 3
git:
  depth: 2
branches:
  only:
    - master
    - dev
script: 
    - xcodebuild -workspace ApiAI.xcworkspace -scheme ApiAITests -sdk iphonesimulator build test
notifications:
  email:
    recipients:
      - dkuragin@ya.ru  
      - kuragin@speaktoit.com